// Generated by   : ImageConverter 565 Online
// Generated from : tet.jpg
// Time generated : Thu, 30 Sep 21 13:39:01 +0200  (Server timezone: CET)
// Image Size     : 135x240 pixels
// Memory usage   : 64800 bytes

// Tetris.h
#ifndef TETRIS_H
#define TETRIS_H

#include <Arduino.h>
#include <TFT_eSPI.h>

struct Point
{
    int X, Y;
};
struct Block
{
    Point square[4][4];
    int numRotate, color;
};
void tetrisSetup(void);
void tetrisLoop();
void Draw();
void PutStartPos();
bool GetSquares(Block block, Point pos, int rot, Point *squares);
void GameOver();
void ClearKeys();
bool KeyPadLoop();
void GetNextPosRot(Point *pnext_pos, int *pnext_rot);
void DeleteLine();
void ReviseScreen(Point next_pos, int next_rot);
void make_block(int n, uint16_t color);

#endif // TETRIS_H
