name: PlatformIO CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Install TFT_eSPI Library
        run: platformio lib -g install "TFT_eSPI" "QRCode"
      - name: Build code
        run: pio ci --board=ttgo-lora32-v1 --lib="."
        env:
          PLATFORMIO_CI_SRC: src/main.cpp src/breakout/breakout.cpp src/presence/presence.cpp src/tetris/tetris.cpp
      - name: List build output
        run: ls -l .pio/build/ttgo-lora32-v1/
